general {
  border_size = 2
}

decoration {
  shadow {
    enabled = true
  }
}

animations {
  animation = borderangle, 1, 80, liner, loop
}

input {
  kb_layout = us,br
  kb_variant = ,abnt2
  kb_options = grp:alt_shift_toggle
}
