general {
  border_size = 2
}

decoration {
  shadow {
    enabled = false
  }
}

animations {
  animation = borderangle, 0, 80, liner, loop
}

input {
  kb_layout = br
  kb_variant = abnt2
  kb_options = 
}

misc {
  vrr = 0
}