# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #


windowrule = opacity 0.9 0.8, match:tag terminal

# No animations for screenshot selection and picker
layerrule = match:namespace selection, no_anim on
layerrule = match:namespace hyprpicker, no_anim on
