# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

windowrule = opacity 0.99 0.90, match:tag browser
windowrule = opacity 0.975 0.95, match:tag projects
windowrule = opacity 0.95 0.90, match:tag im
windowrule = opacity 0.95 0.90, match:tag multimedia
windowrule = opacity 0.95 0.90, match:tag file-manager
windowrule = opacity 0.9 0.75, match:tag terminal
windowrule = opacity 0.95 0.875, match:tag settings
windowrule = opacity 0.95 0.875, match:tag viewer
windowrule = opacity 0.95 0.875, match:tag wallpaper

windowrule = opacity 0.95 0.875, match:class ^(gedit|org\.gnome\.TextEditor|mousepad)$
windowrule = opacity 0.95 0.875, match:class ^(deluge)$
windowrule = opacity 0.95 0.875, match:class ^(seahorse)$
windowrule = opacity 0.95 0.875, match:title ^(Picture-in-Picture)$